'use client';

import React, { useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { X, Zap, Check, Sparkles, Plus, Play, AlertTriangle, Target, BookOpen, ChevronRight, RefreshCw } from 'lucide-react';
import type { JourneyNode } from './JourneyNodeCard';

interface NodeDetailDrawerProps { node: JourneyNode | null; onClose: () => void; onStartPractice: (slug: string) => void; onOpenAiSubtopicModal: () => void; onGenerateAiProblem: (patternTitle: string, subtopicTitle?: string) => void; isGeneratingAi: boolean; generationError?: string | null; }
const SubtopicIcon = ({ index }: { index: number }) => index === 0 ? <Check className="text-emerald-500" size={17} /> : index === 1 ? <Zap className="fill-amber-500 text-amber-500" size={17} /> : index === 2 ? <Target className="text-sky-500" size={17} /> : <AlertTriangle className="text-rose-500" size={17} />;
const MIN_DRAWER_WIDTH = 360;
const MAX_DRAWER_WIDTH = 620;

export const NodeDetailDrawer: React.FC<NodeDetailDrawerProps> = ({ node, onClose, onStartPractice, onOpenAiSubtopicModal, onGenerateAiProblem, isGeneratingAi, generationError }) => {
  const [selectedSubtopicId, setSelectedSubtopicId] = useState<string | null>(null);
  const [drawerWidth, setDrawerWidth] = useState(420);
  const resizeStart = useRef<{ x: number; width: number } | null>(null);
  if (!node) return null;
  const selectedSubtopic = node.subtopics.find((subtopic) => subtopic.id === selectedSubtopicId);
  const focusText = node.bottleneck ?? 'Choose one small skill to strengthen, then apply it in a focused practice set.';
  const startResize = (event: React.PointerEvent<HTMLButtonElement>) => { resizeStart.current = { x: event.clientX, width: drawerWidth }; event.currentTarget.setPointerCapture(event.pointerId); };
  const resize = (event: React.PointerEvent<HTMLButtonElement>) => { if (!resizeStart.current) return; setDrawerWidth(Math.max(MIN_DRAWER_WIDTH, Math.min(MAX_DRAWER_WIDTH, resizeStart.current.width + resizeStart.current.x - event.clientX))); };
  const stopResize = () => { resizeStart.current = null; };
  return <motion.aside initial={{ x: 48, opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: 48, opacity: 0 }} transition={{ type: 'spring', stiffness: 360, damping: 32 }} style={{ '--drawer-width': `${drawerWidth}px` } as React.CSSProperties} className="fixed right-0 top-0 z-40 flex h-full w-full flex-col overflow-y-auto border-l border-[#e8e1d3] bg-[#fffdf8] p-5 shadow-2xl sm:w-[420px] lg:relative lg:w-[var(--drawer-width)] lg:shrink-0">
    <button type="button" aria-label="Resize details sidebar" onPointerDown={startResize} onPointerMove={resize} onPointerUp={stopResize} onPointerCancel={stopResize} className="group absolute inset-y-0 left-0 z-10 hidden w-3 cursor-col-resize touch-none lg:flex lg:items-center lg:justify-center"><span className="h-14 w-1 rounded-full bg-slate-300/70 transition-colors group-hover:bg-amber-400" /></button>
    <div className="space-y-5"><div className="flex items-center justify-between border-b border-[#eee7da] pb-3"><span className="text-xs font-bold text-slate-500">Core patterns <ChevronRight className="inline" size={13} /> <span className="text-slate-800">{node.title}</span></span><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Close details"><X size={18} /></button></div>
      <div className="flex gap-3"><span className="grid h-15 w-15 shrink-0 place-items-center rounded-full border-4 border-[#fff4d6] bg-gradient-to-br from-amber-400 to-orange-500 text-white shadow-md"><Zap size={27} fill="white" /></span><div><h3 className="text-2xl font-black tracking-tight text-[#17263a]">{node.title}</h3><p className="mt-1 text-sm leading-snug text-slate-500">{node.description}</p></div></div>
      <div><div className="mb-2 flex items-end justify-between text-sm font-bold text-slate-600"><span>Mastery</span><span className="text-2xl text-[#e67b1f]">{node.masteryPct}%</span></div><div className="h-3 overflow-hidden rounded-full bg-[#eee9df]"><motion.div initial={{ width: 0 }} animate={{ width: `${node.masteryPct}%` }} transition={{ duration: .65 }} className="h-full rounded-full bg-gradient-to-r from-amber-400 to-orange-500" /></div></div>
      <p className="text-sm font-medium leading-relaxed text-slate-600">{focusText}</p><div className="rounded-2xl border border-[#d6efdc] bg-[#ebf9ed] p-4"><p className="flex items-center gap-2 text-xs font-extrabold text-[#217c50]"><span className="grid h-6 w-6 place-items-center rounded-lg bg-emerald-500 text-white">✦</span>Key learning focus</p><p className="mt-2 pl-8 text-xs leading-relaxed text-[#39715b]">{node.bottleneck ?? 'Build a reliable mental model before increasing difficulty.'}</p></div>
      <section><div className="mb-3 flex items-center justify-between"><h4 className="text-sm font-extrabold text-[#17263a]">Subtopics</h4><button onClick={onOpenAiSubtopicModal} className="inline-flex items-center gap-1 rounded-lg border border-[#e8d8b6] bg-white px-2.5 py-1.5 text-xs font-bold text-[#a85b17] hover:bg-[#fff8e9]"><Plus size={14} /> Generate subtopic</button></div><div className="space-y-2">{node.subtopics.map((subtopic, index) => <button key={subtopic.id} onClick={() => setSelectedSubtopicId(subtopic.id)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left transition ${selectedSubtopicId === subtopic.id ? 'border-amber-300 bg-[#fff8e9]' : 'border-[#eee7da] bg-white hover:border-[#dfd2bf]'}`}><span className="flex items-center gap-3"><SubtopicIcon index={index} /><span><span className="block text-sm font-bold text-slate-800">{subtopic.title}</span><span className="text-xs text-slate-500">{subtopic.problemCount} exercises</span></span></span><span className="flex items-center gap-2 text-sm font-black text-slate-700">{subtopic.masteryPct}%<ChevronRight size={17} className="text-slate-400" /></span></button>)}</div>{selectedSubtopic && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="mt-3 overflow-hidden rounded-xl border border-[#e9dfcf] bg-white p-3"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-extrabold text-slate-700">{selectedSubtopic.title} problems</p><button onClick={() => onGenerateAiProblem(node.title, selectedSubtopic.title)} disabled={isGeneratingAi} className="inline-flex items-center gap-1 text-xs font-bold text-[#a85b17] disabled:opacity-60">{isGeneratingAi ? <RefreshCw size={13} className="animate-spin" /> : <Sparkles size={13} />}Generate new problem</button></div>{selectedSubtopic.problems?.length ? <div className="space-y-1.5">{selectedSubtopic.problems.map((problem) => <button key={`${problem.slug}-${problem.title}`} onClick={() => onStartPractice(problem.slug)} className="flex w-full items-center justify-between rounded-lg bg-[#faf7f1] px-3 py-2 text-left"><span><span className="block text-xs font-bold text-slate-700">{problem.title}</span><span className="text-[10px] font-bold text-slate-400">{problem.difficulty}</span></span><Play size={14} className="text-[#e67b1f]" fill="currentColor" /></button>)}</div> : <p className="text-xs leading-relaxed text-slate-500">No problems yet. Generate a focused problem for this subtopic.</p>}</motion.div>}</section>
    </div><div className="mt-5 space-y-2 border-t border-[#eee7da] pt-4">{generationError && <p role="alert" className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{generationError}</p>}<button onClick={() => onStartPractice(selectedSubtopic?.problems?.[0]?.slug ?? node.defaultSlug)} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-amber-400 to-orange-500 py-3.5 text-sm font-black text-white shadow-md shadow-orange-200"><Play size={17} fill="white" />Continue learning</button><div className="grid grid-cols-2 gap-2"><button onClick={() => onGenerateAiProblem(node.title, selectedSubtopic?.title)} disabled={isGeneratingAi} className="flex items-center justify-center gap-1.5 rounded-xl border border-[#eadcc7] bg-white py-2.5 text-xs font-bold text-[#9a5618] hover:bg-[#fff8ec] disabled:opacity-60">{isGeneratingAi ? <RefreshCw size={15} className="animate-spin" /> : <Sparkles size={15} />}Generate practice</button><button onClick={() => onStartPractice(selectedSubtopic?.problems?.[0]?.slug ?? node.defaultSlug)} className="flex items-center justify-center gap-1.5 rounded-xl border border-[#eadcc7] bg-white py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-50"><BookOpen size={15} />Problem set</button></div></div>
  </motion.aside>;
};
export default NodeDetailDrawer;
